import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase";
import { requireAuthFromToken } from "@/lib/auth";

export const dynamic = "force-dynamic";

/**
 * GET /api/search?q=...&limit=10
 * Semantic search over companies using pgvector cosine similarity.
 * Requires the company to have an embedding (generated by worker).
 */
export async function GET(req: Request) {
  try {
    const cookie = req.headers.get("cookie") || "";
    const tokenMatch = cookie.match(/knight_token=([^;]+)/);
    if (!tokenMatch) throw new Error("Unauthorized");
    const { org } = await requireAuthFromToken(tokenMatch[1]);

    const url = new URL(req.url);
    const query = url.searchParams.get("q");
    const limit = Math.min(parseInt(url.searchParams.get("limit") || "10"), 50);

    if (!query || query.trim().length === 0) {
      return NextResponse.json({ error: "Query is required" }, { status: 400 });
    }

    const supabase = createServiceClient();

    // Generate embedding for the search query using Cohere
    const cohereKey = process.env.COHERE_API_KEY;
    if (!cohereKey) {
      return NextResponse.json({ error: "Embedding service not configured" }, { status: 500 });
    }

    const { CohereClient } = await import("cohere-ai");
    const cohere = new CohereClient({ token: cohereKey });

    const response = await cohere.embed({
      texts: [query.slice(0, 2000)],
      model: "embed-english-v3.0",
      inputType: "search_query",
      embeddingTypes: ["float"],
    });

    const embeddings = response.embeddings as any;
    const queryEmbedding = Array.isArray(embeddings) ? embeddings[0] : embeddings.float?.[0];
    if (!queryEmbedding) {
      return NextResponse.json({ error: "Failed to generate embedding" }, { status: 500 });
    }

    // Search using pgvector cosine similarity
    const { data: results, error } = await supabase.rpc("search_companies", {
      query_embedding: JSON.stringify(queryEmbedding),
      match_count: limit,
      org_id_filter: org.id,
    });

    if (error) {
      // Fallback: raw SQL query if RPC not set up
      const { data: fallback, error: fbErr } = await supabase
        .from("companies")
        .select("id, name, website_url, industry, lead_score, status, ai_pitch, created_at, embedding")
        .eq("org_id", org.id)
        .not("embedding", "is", null)
        .limit(limit);

      if (fbErr) throw fbErr;

      // Manual cosine similarity for fallback
      const scored = (fallback || []).map((c) => {
        const emb = typeof c.embedding === "string" ? JSON.parse(c.embedding) : c.embedding;
        if (!emb) return { ...c, similarity: 0 };
        const sim = cosineSimilarity(queryEmbedding, emb);
        return { ...c, similarity: sim };
      });

      scored.sort((a, b) => b.similarity - a.similarity);
      return NextResponse.json({ results: scored.slice(0, limit), query });
    }

    return NextResponse.json({ results, query });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

function cosineSimilarity(a: number[], b: number[]): number {
  if (!a || !b || a.length !== b.length) return 0;
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}
